// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: repoupdater.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RepoUpdaterServiceClient is the client API for RepoUpdaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepoUpdaterServiceClient interface {
}

type repoUpdaterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepoUpdaterServiceClient(cc grpc.ClientConnInterface) RepoUpdaterServiceClient {
	return &repoUpdaterServiceClient{cc}
}

// RepoUpdaterServiceServer is the server API for RepoUpdaterService service.
// All implementations must embed UnimplementedRepoUpdaterServiceServer
// for forward compatibility
type RepoUpdaterServiceServer interface {
	mustEmbedUnimplementedRepoUpdaterServiceServer()
}

// UnimplementedRepoUpdaterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRepoUpdaterServiceServer struct {
}

func (UnimplementedRepoUpdaterServiceServer) mustEmbedUnimplementedRepoUpdaterServiceServer() {}

// UnsafeRepoUpdaterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepoUpdaterServiceServer will
// result in compilation errors.
type UnsafeRepoUpdaterServiceServer interface {
	mustEmbedUnimplementedRepoUpdaterServiceServer()
}

func RegisterRepoUpdaterServiceServer(s grpc.ServiceRegistrar, srv RepoUpdaterServiceServer) {
	s.RegisterService(&RepoUpdaterService_ServiceDesc, srv)
}

// RepoUpdaterService_ServiceDesc is the grpc.ServiceDesc for RepoUpdaterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepoUpdaterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repoupdater.v1.RepoUpdaterService",
	HandlerType: (*RepoUpdaterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "repoupdater.proto",
}
